sudo: false

git:
  depth: 3

branches:
  only:
    - next
    - master

language: node_js

cache:
  npm: true

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint ✨
      script: npm run lint:ci
      node_js: lts/*

    - stage: test 👩🏽‍💻
      os: linux
      script: npm run test:cov
      node_js: node

    - os: linux
      script: npm run test:cov
      node_js: lts/*

    - os: windows
      script: npm run test:cov
      node_js: node

    - os: windows
      script: npm run test:cov
      node_js: lts/*
